server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookstore
          uri: lb://bookstore
          predicates:
            - Path=/bookstore/**
        - id: bookware
          uri: lb://bookware
          predicates:
            - Path=/bookware/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
